### ISSUE TITLE
Readme file missing crucial headers.

### ISSUE THREAD

**Issue by kalbek** [BANCUNGUYE66/Portfolio#3]
Peer to peer code review first issue.

**Comment by BANCUNGUYE66** [comment]
@kalbek Can you please let me know where exactly

**Comment by kalbek** [comment]
Under getting started part the microverse template has, usage run tests and deployment

**Comment by Kgomotso196** [comment]
Don't forget to remove the comments on your README.md after modifying it.

**Comment by yin-ka** [comment]
I appreciate the fact that your codes were organised structurally. However, I would suggest you make use of comments to aid the reading of your codes.

**Comment by Kgomotso196** [comment]
Kindly do not forget to remove the comments on your README.md after modifying it.

**Comment by kalbek** [comment]
Thank you, now the issue is resolved.
